import { type NextPage } from "next";
import Head from "next/head";

import Login from "../../components/login/login";
import Index from "../../components/index/index";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status == "authenticated") {
    return (
        <Index />
    );
  }

  return (
    <>
      <Head>
        <title>Chillhub - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/chillhub.png" />
      </Head>
      <main></main>
    </>
  );
};

export default Home;
