import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

import Login from "../../components/login/login";
import Index from "../../components/index/index";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status == "authenticated") {
    return (
        <Index />
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        
        <Login />
        
      </main>
    </>
  );
};

export default Home;
